require("plugins")
require("lsp-config")
require("telescope-config")
require("file-tree")
require("editor-settings")
require("compe-config")
require("kommentary-config")
require("lastplace")
require("mappings")
require("gitsigns-config")
require("spectre-config")
require("term-config")
require("lightspeed-config")
require("stay-centered")
require("onedark").setup()
require("nvim-peekup.config")
require("dap-config")
require("dap-ui")
vim.api.nvim_command("autocmd TermOpen * :lua require('util.change-terminal-ftype').changeTerminalFileType()")
-- require("util.change-terminal-ftype")
-- require("indent-config")
