local lspsaga = require "lspsaga"
-- lspsaga.init_lsp_saga()
lspsaga.setup {
  debug = false,
  use_saga_diagnostic_sign = true,
  error_sign = "",
  warn_sign = "",
  hint_sign = "",
  infor_sign = "",
  diagnostic_header_icon = "   ",
  code_action_icon = " ",
  code_action_prompt = { enable = true, sign = true, sign_priority = 40, virtual_text = true },
  finder_definition_icon = "  ",
  finder_reference_icon = "  ",
  max_preview_lines = 20,
  finder_action_keys = {
    open = "o",
    vsplit = "s",
    split = "i",
    quit = "<Esc>",
    scroll_down = "<C-f>",
    scroll_up = "<C-g>",
  },
  code_action_keys = { quit = "<Esc>", exec = "<CR>" },
  rename_action_keys = { quit = "<Esc>", exec = "<CR>" },
  definition_preview_icon = "  ",
  border_style = "single",
  rename_prompt_prefix = "➤",
  server_filetype_map = {},
  diagnostic_prefix_format = "%d. ",
}
