local toc = require("table-of-contents.mappings-toc")
require("octo").setup(
  {
    user_icon = " ", -- user icon
    file_panel = {
      size = 10, -- changed files panel rows
      use_icons = true, -- use web-devicons in file panel
    },
    github_hostname = "", -- GitHub Enterprise host
    timeline_marker = "", -- timeline marker
    timeline_indent = "2", -- timeline indentation
    snippet_context_lines = 4, -- number or lines around commented lines
    left_bubble_delimiter = "", -- Bubble delimiter
    right_bubble_delimiter = "", -- Bubble delimiter
    reaction_viewer_hint_icon = "", -- marker for user reactions
    default_remote = { "upstream", "origin" }, -- order to try remotes
    mappings = {
      issue = {
        reload = toc.octo.reload, -- reload issue
        list_issues = toc.issue.list, -- list open issues on same repo
        copy_url = toc.issue.copy_url, -- copy url to system clipboard
        add_comment = toc.octo.add_comment, -- add comment
        open_in_browser = toc.octo.browser, -- open issue in browser
        next_comment = toc.octo.next_comment, -- go to next comment
        prev_comment = toc.octo.prev_comment, -- go to previous comment
        delete_comment = toc.octo.delete_comment, -- delete comment
        add_label = nil, -- add label
        goto_issue = nil, -- navigate to a local repo issue
        react_eyes = nil, -- add/remove 👀 reaction
        react_heart = nil, -- add/remove ❤️ reaction
        react_laugh = nil, -- add/remove 😄 reaction
        close_issue = nil, -- close issue
        react_hooray = nil, -- add/remove 🎉 reaction
        react_rocket = nil, -- add/remove 🚀 reaction
        reopen_issue = nil, -- reopen issue
        add_assignee = nil, -- add assignee
        create_label = nil, -- create label
        remove_label = nil, -- remove label
        react_confused = nil, -- add/remove 😕 reaction
        remove_assignee = nil, -- remove assignee
        react_thumbs_up = nil, -- add/remove 👍 reaction
        react_thumbs_down = nil, -- add/remove 👎 reaction
      },
      pull_request = {
        reload = toc.octo.reload, -- reload PR
        copy_url = toc.octo.copy_url, -- copy url to system clipboard
        list_issues = toc.issue.list, -- list open issues on same repo
        merge_pr = toc.pull_request.merge, -- merge PR
        add_comment = toc.octo.add_comment, -- add comment
        open_in_browser = toc.octo.browser, -- open PR in browser
        prev_comment = toc.octo.prev_comment, -- go to previous comment
        next_comment = toc.octo.next_comment, -- go to next comment
        checkout_pr = toc.pull_request.checkout, -- checkout PR
        list_commits = toc.pull_request.list_commits, -- list PR commits
        show_pr_diff = toc.pull_request.show_pr_diff, -- show PR diff
        add_label = nil, -- add label
        goto_issue = nil, -- navigate to a local repo issue
        react_eyes = nil, -- add/remove 👀 reaction
        react_heart = nil, -- add/remove ❤️ reaction
        react_laugh = nil, -- add/remove 😄 reaction
        close_issue = nil, -- close issue
        react_hooray = nil, -- add/remove 🎉 reaction
        add_reviewer = nil, -- add reviewer
        react_rocket = nil, -- add/remove 🚀 reaction
        reopen_issue = nil, -- reopen issue
        add_assignee = nil, -- add assignee
        create_label = nil, -- create label
        remove_label = nil, -- remove label
        delete_comment = nil, -- delete comment
        react_confused = nil, -- add/remove 😕 reaction
        remove_reviewer = nil, -- remove reviewer request
        remove_assignee = nil, -- remove assignee
        react_thumbs_up = nil, -- add/remove 👍 reaction
        react_thumbs_down = nil, -- add/remove 👎 reaction
        list_changed_files = nil, -- list PR changed files
      },
      review_thread = {
        reload = toc.octo.reload, -- reload PR
        copy_url = toc.octo.copy_url, -- copy url to system clipboard
        list_issues = toc.issue.list, -- list open issues on same repo
        merge_pr = toc.pull_request.merge, -- merge PR
        add_comment = toc.octo.add_comment, -- add comment
        open_in_browser = toc.octo.browser, -- open PR in browser
        prev_comment = toc.octo.prev_comment, -- go to previous comment
        next_comment = toc.octo.next_comment, -- go to next comment
        close_review_tab = toc.review.close_tab, -- close review tab
        checkout_pr = toc.pull_request.checkout, -- checkout PR
        add_suggestion = toc.review.add_selection, -- add suggestion
        select_next_entry = toc.review.next_entry, -- move to previous changed file
        select_prev_entry = toc.review.prev_entry, -- move to next changed file
        list_commits = toc.pull_request.list_commits, -- list PR commits
        show_pr_diff = toc.pull_request.show_pr_diff, -- show PR diff
        add_label = nil, -- add label
        goto_issue = nil, -- navigate to a local repo issue
        react_eyes = nil, -- add/remove 👀 reaction
        react_heart = nil, -- add/remove ❤️ reaction
        react_laugh = nil, -- add/remove 😄 reaction
        close_issue = nil, -- close issue
        react_hooray = nil, -- add/remove 🎉 reaction
        add_reviewer = nil, -- add reviewer
        react_rocket = nil, -- add/remove 🚀 reaction
        reopen_issue = nil, -- reopen issue
        add_assignee = nil, -- add assignee
        create_label = nil, -- create label
        remove_label = nil, -- remove label
        delete_comment = nil, -- delete comment
        react_confused = nil, -- add/remove 😕 reaction
        remove_reviewer = nil, -- remove reviewer request
        remove_assignee = nil, -- remove assignee
        react_thumbs_up = nil, -- add/remove 👍 reaction
        react_thumbs_down = nil, -- add/remove 👎 reaction
        list_changed_files = nil, -- list PR changed files
      },
      submit_win = {
        approve_review = toc.review.approve, -- approve review
        comment_review = toc.octo.add_comment, -- comment review
        close_review_tab = toc.review.close_tab, -- close review tab
        request_changes = nil, -- request changes review
      },
      review_diff = {
        focus_files = toc.review.focus, -- move focus to changed file panel
        toggle_files = toc.review.files, -- hide/show changed files panel
        next_thread = toc.review.next_thread, -- move to next thread
        prev_thread = toc.review.prev_thread, -- move to previous thread
        close_review_tab = toc.review.close_tab, -- close review tab
        select_next_entry = toc.review.next_entry, -- move to previous changed file
        select_prev_entry = toc.review.prev_entry, -- move to next changed file
        add_review_comment = toc.octo.add_comment, -- add a new review comment
        add_review_suggestion = toc.review.add_suggestion, -- add a new review suggestion
        toggle_viewed = nil, -- toggle viewer viewed state
      },
      file_panel = {
        focus_files = toc.review.focus, -- move focus to changed file panel
        refresh_files = toc.octo.reload, -- refresh changed files panel
        toggle_files = toc.review.files, -- hide/show changed files panel
        next_entry = toc.octo_files.next, -- move to next changed file
        prev_entry = toc.octo_files.prev, -- move to previous changed file
        select_entry = toc.octo_files.select, -- show selected changed file diffs
        close_review_tab = toc.review.close_tab, -- close review tab
        select_next_entry = toc.review.next_entry, -- move to previous changed file
        select_prev_entry = toc.review.prev_entry, -- move to next changed file
        toggle_viewed = nil, -- toggle viewer viewed state
      },
    },
  }
)
